version: "2.2"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: slurm-docker-cluster:17.11.7
    command: ["slurmdbd", "-D", "-v"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - ./etc_slurm:/etc/slurm
              #- etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    image: slurm-docker-cluster:17.11.7
    command: ["slurmctld", "-D", "-vvv", "-c", "-i"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - ./home:/home
      - ./etc_slurm:/etc/slurm
              #- etc_slurm:/etc/slurm
      - ./data:/data
        #      -- slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    ports:
      - "6817:6817"
    depends_on:
      - "slurmdbd"

  c1:
    image: slurm-docker-cluster:17.11.7
    command: ["slurmd", "-D", "-vvv", "-b"]
    hostname: c1
    container_name: c1
    volumes:
      - etc_munge:/etc/munge
      - ./home:/home
      - ./etc_slurm:/etc/slurm
              #- etc_slurm:/etc/slurm
      - ./data:/data
        #      -- slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  c2:
    image: slurm-docker-cluster:17.11.7
    command: ["slurmd", "-D", "-vvv", "-b"]
    hostname: c2
    container_name: c2
    volumes:
      - etc_munge:/etc/munge
      - ./home:/home
      - ./etc_slurm:/etc/slurm
        #- etc_slurm:/etc/slurm
      - ./data:/data
#      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

volumes:
  etc_munge:
          #  etc_slurm:
#  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
